### ISSUE TITLE
Add contour lines

### ISSUE THREAD

**Issue by rugk** [oobrien/oomap#29]
If you need a data source, maybe look at OsmAnd, they have some data and it can be used in their applications. (AFAIK) Worldwide…

**Comment by oobrien** [comment]
It is possible to derive contour lines from global DEMs, although the process of doing this, and in particularly smoothing the lines is very computationally intensive, so not proposing adding this at this time. I will keep this bug open for now in case an external source of contours lines appears. OsmAnd have done this process, but it is involved, which is why they charge for it.

**Comment by rugk** [comment]
> OsmAnd have done this process, but it is involved

It is _what_? AFAIK you can use them in the F-Droid version of OSM, so that is not too bad.

**Comment by hholzgra** [comment]
I got the contour line for my print.get-map.org site from the maintainers of OpenSnowMap, it is a PostGIS dump that when imported creates a ~500GB contours table. This was a while a go already, but they replied quickly back then and were happily willing to share the data on request.

**Comment by cadnant** [comment]
Worth revisiting?  Can use Phyghtmap to retrieve SRTM data and plot contours on-the-fly.  cadnant/oomap@07d8a389bd739600f51b4936f612e021a8012ebe

**Comment by oobrien** [comment]
Definitely

**Comment by cadnant** [comment]
Contours enabled (more or less) globally through on-the-fly requests for SRTM or Copernicus height data, then generation and smoothing of the contours themselves.  And yes, it was fairly involved 😀. See #69 .
Additionally, LIDAR data added where easily available for bulk download.
